x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "3"

services:
  nginx:
    image: birdlense_nginx:latest
    container_name: birdlense_nginx
    depends_on:
      - web
      - ui
    ports:
      - "80:8080"
      - "8081:8081"
    volumes:
      - ./data:/srv/data
      - /var/lib/docker/containers:/docker_logs:ro # Expose logs in nginx
    logging: *default-logging

  processor:
    image: birdlense_processor:latest
    container_name: birdlense_processor
    volumes:
      - /dev/shm:/dev/shm # used by audio recording
      - /run/udev:/run/udev:ro
      - ./app_config:/app/src/app_config
      - ./data:/app/data
    devices:
      - /dev/video0 # camera
      - /dev/video10 # V4L2 H264 encoder (hardware)
      - /dev/video11 # V4L2 H264 encoder (hardware)
      - /dev/video12 # V4L2 H264 encoder (hardware)
      - /dev/video18 # V4L2 H264 stateless decoder
      - /dev/video19 # V4L2 H264 stateless decoder
      - /dev/video31 # ISP
      - /dev/snd # audio
      - /dev/bus/usb # audio
      - /dev/gpiochip0:/dev/gpiochip4 # To address a bug in lgpio described inhttps://github.com/gpiozero/gpiozero/issues/1166
    ipc: host
    environment:
      - API_URL_BASE=http://web:8000/api/processor
      - LD_LIBRARY_PATH=/opt/vc/lib
      - ENABLE_AUDIO_PROCESSING=${ENABLE_AUDIO_PROCESSING:-true}
    command: python src/main.py
    privileged: true # unfortunately, it's required for picamera2 to access pi camera
    depends_on:
      - web
    logging: *default-logging

  web:
    image: birdlense_web:latest
    container_name: birdlense_web
    depends_on:
      - ntfy
    environment:
      - BIRDLENSE_DOMAIN=${BIRDLENSE_DOMAIN:-birdlense.local}
    volumes:
      - /proc:/host/proc:ro # Access CPU/memory stats
      - /sys:/host/sys:ro # Access temperature sensors
      - ./app_config:/app/app_config
      - ./data:/app/data
    logging: *default-logging

  ui:
    image: birdlense_ui:latest
    container_name: birdlense_ui
    environment:
      - VITE_BASE_URL=${VITE_BASE_URL:-}
    logging: *default-logging

  ntfy:
    container_name: birdlense_ntfy
    image: binwiederhier/ntfy
    command:
      - serve
    environment:
      TZ: "America/New_York" # optional: set desired timezone
      NTFY_BEHIND_PROXY: "true"
      NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh"
      NTFY_BASE_URL: "${NTFY_BASE_URL:-http://birdlense.local:8081}"
    logging: *default-logging
